apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: webapp-vs
spec:
  host: webapp.example.com
  tls:
    secret: kibana-nic-secret
    redirect:
      enable: true
  upstreams:
  - name: webapp
    service: webapp-svc
    port: 80
    tls:
      enable: true
  routes:
  - path: /
    policies:
    - name: ad-oidc-policy
    action:
      pass: webapp